import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, Share2, Copy, Check, Link as LinkIcon, ExternalLink, BookOpen } from 'lucide-react';
import { AudioPlayer } from '../components/AudioPlayer';
import { ChapterPill } from '../components/ChapterPill';
import { StepIndicator } from '../components/StepIndicator';
import { useAppContext } from '../context/AppContext';
import { useReferences } from '../context/ReferencesContext';

// Parse "HH:MM:SS" or "MM:SS" timestamp strings into total seconds
function parseTimestamp(ts: string): number {
    if (!ts) return 0;
    const parts = ts.split(':').map(Number);
    if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
    if (parts.length === 2) return parts[0] * 60 + parts[1];
    return 0;
}

// Convert absolute seconds back to MM:SS or HH:MM:SS
function formatTimestamp(totalSeconds: number): string {
    const h = Math.floor(totalSeconds / 3600);
    const m = Math.floor((totalSeconds % 3600) / 60);
    const s = Math.floor(totalSeconds % 60);
    if (h > 0) {
        return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    }
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}



export function Listen() {
    const navigate = useNavigate();
    const { script, audioUrl, sourcePapers } = useAppContext();
    const { references } = useReferences();

    const [activeDialogue, setActiveDialogue] = useState(-1);
    const [activeChapter, setActiveChapter] = useState(0);
    const [autoScroll, setAutoScroll] = useState(true);
    const [currentTime, setCurrentTime] = useState(0);
    const [copied, setCopied] = useState(false);
    const [shared, setShared] = useState(false);
    const transcriptRef = useRef<HTMLDivElement>(null);
    const audioRef = useRef<HTMLAudioElement | null>(null);

    const handleShare = async () => {
        const shareData = {
            title: script?.title ?? 'PaperCast Episode',
            text: `🎙️ Listen to "${script?.title}" — generated by PaperCast`,
            url: window.location.href,
        };
        if (navigator.share && navigator.canShare(shareData)) {
            try { await navigator.share(shareData); } catch { /* user cancelled */ }
        } else {
            // Fallback: copy the URL to clipboard
            await navigator.clipboard.writeText(window.location.href);
            setShared(true);
            setTimeout(() => setShared(false), 2000);
        }
    };

    const handleCopyTranscript = async () => {
        if (!script) return;
        const lines = script.chapters.flatMap(ch => [
            `\n── ${ch.title} ──`,
            ...ch.dialogues.map(d => `[${d.timestamp}] ${d.speaker.toUpperCase()}: ${d.text}`)
        ]);
        const text = `${script.title}\n${'─'.repeat(60)}\n${lines.join('\n')}`;
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    // Early return UI component, but we'll conditionally render it later so hooks run first.

    const rawDialogues = script ? script.chapters.flatMap((c, cIdx) =>
        c.dialogues.map((d) => ({
            ...d,
            chapterIndex: cIdx,
            isAlex: d.speaker.toLowerCase() === 'alex',
            startSeconds: parseTimestamp(d.timestamp)
        }))
    ) : [];

    const allDialogues: (typeof rawDialogues[0] & { isContinuation?: boolean })[] = [];

    for (let i = 0; i < rawDialogues.length; i++) {
        const current = rawDialogues[i];
        // We removed text chunking here to prevent any accidental drops of text 
        // that lack standard punctuation. We now render exact AI dialogues.
        allDialogues.push({
            ...current,
            startSeconds: current.startSeconds,
            timestamp: formatTimestamp(current.startSeconds),
            isContinuation: false
        });
    }

    // Sync active dialogue based on current playback time
    useEffect(() => {
        let activeIdx = -1;
        for (let i = 0; i < allDialogues.length; i++) {
            if (currentTime >= allDialogues[i].startSeconds) {
                activeIdx = i;
            }
        }
        setActiveDialogue(activeIdx);

        // Update active chapter
        if (activeIdx >= 0) {
            setActiveChapter(allDialogues[activeIdx].chapterIndex);
        }
    }, [currentTime, allDialogues]);

    // Auto-scroll active dialogue into view
    useEffect(() => {
        if (!autoScroll || !transcriptRef.current) return;
        const active = transcriptRef.current.querySelector('[data-active="true"]');
        if (active) {
            active.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }, [activeDialogue, autoScroll]);

    // Seek audio to a specific dialogue when transcript is clicked
    const handleTranscriptClick = (dialogue: typeof allDialogues[0]) => {
        if (audioRef.current) {
            audioRef.current.currentTime = dialogue.startSeconds;
            // If paused, start playing
            audioRef.current.play().catch(() => { });
            setCurrentTime(dialogue.startSeconds);
        }
    };

    if (!script || !audioUrl) {
        return (
            <div className="min-h-screen flex items-center justify-center flex-col gap-4 text-brand-muted">
                <h2 className="text-xl">No audio available.</h2>
                <button onClick={() => navigate('/edit')} className="text-brand-primary hover:underline">Go back to Editor</button>
            </div>
        );
    }

    return (
        <div className="min-h-screen pt-24 pb-32 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
            <StepIndicator currentStep={5} />

            <div className="text-center mb-10">
                <h1 className="text-3xl md:text-4xl font-display font-bold mb-3">{script.title}</h1>
                <p className="text-brand-muted text-lg font-mono mb-4">Total Duration: {script.estimatedDuration}</p>

                {sourcePapers && sourcePapers.length > 0 && (
                    <div className="flex flex-wrap items-center justify-center gap-2 mt-4">
                        <div className="flex items-center gap-2 text-xs font-bold text-brand-muted uppercase tracking-widest mr-2">
                            <LinkIcon className="w-3.5 h-3.5" /> Sources
                        </div>
                        {sourcePapers.map((paper, i) => (
                            paper.url ? (
                                <a
                                    key={i}
                                    href={paper.url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-md bg-brand-secondary/10 text-brand-secondary border border-brand-secondary/20 hover:bg-brand-secondary/20 transition-colors"
                                >
                                    {paper.id ? `arXiv:${paper.id}` : (paper.title || `Paper ${i + 1}`)}
                                    <ExternalLink className="w-3 h-3" />
                                </a>
                            ) : (
                                <span key={i} className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-md bg-brand-muted/10 text-brand-muted border border-brand-border">
                                    {paper.title || `Uploaded Paper ${i + 1}`}
                                </span>
                            )
                        ))}
                    </div>
                )}
            </div>

            <div className="mb-12">
                <AudioPlayer
                    audioUrl={audioUrl}
                    title={script.title}
                    duration={script.estimatedDuration}
                    audioRef={audioRef}
                    onTimeUpdate={(t) => setCurrentTime(t)}
                />
            </div>

            <div className="mb-8">
                <div className="flex items-center justify-between mb-4">
                    <h2 className="text-xs font-bold text-brand-muted tracking-widest uppercase">Chapters</h2>
                    <div className="flex items-center gap-2">
                        <span className="text-xs text-brand-muted mr-2">Auto-scroll</span>
                        <button
                            onClick={() => setAutoScroll(!autoScroll)}
                            className={`w-10 h-5 rounded-full p-1 transition-colors ${autoScroll ? 'bg-brand-primary' : 'bg-brand-border'}`}
                        >
                            <div className={`w-3 h-3 rounded-full bg-white transition-transform ${autoScroll ? 'translate-x-5' : 'translate-x-0'}`} />
                        </button>
                    </div>
                </div>

                <div className="flex overflow-x-auto pb-4 gap-3 no-scrollbar mask-edges">
                    {script.chapters.map((chapter, i) => (
                        <ChapterPill
                            key={i}
                            title={chapter.title}
                            timestamp={chapter.dialogues[0]?.timestamp || "00:00"}
                            isActive={activeChapter === i}
                            onClick={() => {
                                setActiveChapter(i);
                                // Jump audio to first dialogue of this chapter
                                const firstDialogue = allDialogues.find(d => d.chapterIndex === i);
                                if (firstDialogue) handleTranscriptClick(firstDialogue);
                            }}
                        />
                    ))}
                </div>
            </div>

            {/* Live Transcript Feature */}
            <div className="bg-brand-card/50 border border-brand-border rounded-3xl p-6 sm:p-10 relative overflow-hidden">
                <div className="absolute top-0 left-0 right-0 h-16 bg-gradient-to-b from-brand-card/50 to-transparent z-10 pointer-events-none" />

                <div
                    ref={transcriptRef}
                    className="space-y-8 relative z-0 h-[500px] overflow-y-auto pr-4 custom-scrollbar"
                >
                    {allDialogues.map((dialogue, idx) => {
                        const state = idx === activeDialogue ? 'active' : idx < activeDialogue ? 'past' : 'future';

                        return (
                            <div
                                key={idx}
                                data-active={state === 'active'}
                                onClick={() => handleTranscriptClick(dialogue)}
                                title="Click to jump to this part"
                                className={`flex items-start gap-4 transition-all duration-500 cursor-pointer group
                   ${state === 'active'
                                        ? 'opacity-100 scale-100 filter drop-shadow-[0_0_15px_rgba(255,255,255,0.1)]'
                                        : state === 'past'
                                            ? 'opacity-40 scale-95 grayscale hover:opacity-70 hover:grayscale-0'
                                            : 'opacity-60 scale-95 hover:opacity-80'
                                    }
                   ${!dialogue.isAlex ? 'flex-row-reverse text-right' : ''}
                 `}
                            >
                                <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 font-bold border-2 transition-all
                   ${(dialogue as any).isContinuation ? 'opacity-0' : ''}
                   ${dialogue.isAlex
                                        ? state === 'active' ? 'bg-brand-primary text-white border-brand-primary' : 'bg-brand-accent-alex text-brand-primary border-brand-border group-hover:border-brand-primary'
                                        : state === 'active' ? 'bg-brand-secondary text-brand-bg border-brand-secondary' : 'bg-brand-accent-sam text-brand-secondary border-brand-border group-hover:border-brand-secondary'
                                    }
                 `}>
                                    {dialogue.isAlex ? 'A' : 'S'}
                                </div>

                                <div className={`flex-1 rounded-xl transition-all duration-300 ${state === 'active' ? 'bg-white/5 border border-white/10 p-4' : 'p-2 group-hover:bg-white/3'}`}>
                                    <div className="flex items-center gap-2 mb-1.5">
                                        <span className="font-mono text-xs text-brand-muted">{dialogue.timestamp}</span>
                                        {state !== 'active' && (
                                            <span className="opacity-0 group-hover:opacity-100 transition-opacity text-[10px] text-brand-muted/70 font-mono">
                                                ▶ click to jump
                                            </span>
                                        )}
                                    </div>
                                    <p className={`text-lg leading-relaxed ${state === 'active' ? 'text-white font-medium' : 'text-brand-text'}`}>
                                        {dialogue.text}
                                    </p>
                                </div>
                            </div>
                        );
                    })}
                </div>

                <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-brand-card/90 to-transparent z-10 pointer-events-none" />
            </div>

            {/* 📚 References Section */}
            <div className="mt-12 mb-8">
                <div className="mb-6">
                    <h2 className="text-xl font-display font-bold flex items-center gap-2">
                        <BookOpen className="w-5 h-5 text-brand-primary" />
                        📚 References
                    </h2>
                    <p className="text-brand-muted text-sm mt-1">Research papers used to generate this podcast</p>
                </div>

                {references.length === 0 ? (
                    <div className="bg-brand-card/50 border border-brand-border rounded-2xl p-6 text-center">
                        <p className="text-brand-muted text-sm">
                            This podcast was generated from a manually uploaded PDF. No arXiv references available.
                        </p>
                    </div>
                ) : (
                    <div className="space-y-4">
                        {references.map((ref, i) => {
                            const badgeStyles = {
                                primary: { bg: 'bg-[#6C63FF]/15', text: 'text-[#6C63FF]', border: 'border-[#6C63FF]/30', label: 'Primary Paper', leftBorder: '#6C63FF' },
                                secondary: { bg: 'bg-[#00D4AA]/15', text: 'text-[#00D4AA]', border: 'border-[#00D4AA]/30', label: 'Second Paper', leftBorder: '#00D4AA' },
                                debate: { bg: 'bg-orange-500/15', text: 'text-orange-400', border: 'border-orange-500/30', label: 'Debate Paper', leftBorder: '#f97316' },
                            };
                            const badge = badgeStyles[ref.usedAs];

                            return (
                                <div key={ref.id} className="group">
                                    {/* Citation Card */}
                                    <div
                                        className="bg-[#12121A] border border-[#1E1E2E] rounded-2xl p-5 transition-all hover:border-brand-muted/30"
                                        style={{ borderLeftWidth: 3, borderLeftColor: badge.leftBorder }}
                                    >
                                        <div className="flex items-start justify-between gap-4">
                                            <div className="flex-1 min-w-0">
                                                <div className="flex items-center gap-2 mb-2">
                                                    <span className="text-brand-muted font-mono text-xs font-bold">[{i + 1}]</span>
                                                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${badge.bg} ${badge.text} ${badge.border} border`}>
                                                        {badge.label}
                                                    </span>
                                                </div>
                                                <a
                                                    href={ref.arxivUrl}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="text-white font-semibold text-sm hover:text-brand-primary transition-colors leading-snug block mb-2"
                                                >
                                                    {ref.title}
                                                </a>
                                                {ref.authors.length > 0 && (
                                                    <p className="text-brand-muted text-xs mb-1">
                                                        {ref.authors.map(a => a.name).join(', ')}
                                                    </p>
                                                )}
                                                {ref.year && (
                                                    <p className="text-brand-muted text-xs font-mono">{ref.year}</p>
                                                )}
                                            </div>
                                        </div>

                                        <div className="flex items-center gap-2 mt-4">
                                            <a
                                                href={ref.arxivUrl}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-brand-border hover:border-brand-primary text-brand-muted hover:text-brand-primary text-xs font-medium transition-all"
                                            >
                                                View on arXiv <ExternalLink className="w-3 h-3" />
                                            </a>
                                            {ref.pdfUrl && (
                                                <a
                                                    href={ref.pdfUrl}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-brand-border hover:border-brand-muted text-brand-muted hover:text-brand-text text-xs font-medium transition-all"
                                                >
                                                    <Download className="w-3 h-3" /> Download PDF
                                                </a>
                                            )}
                                        </div>
                                    </div>

                                    {/* Academic Citation Format */}
                                    <p className="text-brand-muted/60 text-[11px] font-mono mt-2 pl-4">
                                        [{i + 1}] {ref.authors.length > 0 ? ref.authors.map(a => a.name).join(', ') + '. ' : ''}
                                        "{ref.title}." {ref.year ? `${ref.year}. ` : ''}arXiv:{ref.id}
                                    </p>
                                </div>
                            );
                        })}
                    </div>
                )}
            </div>

            {/* Sticky Bottom Bar for Export */}
            <div className="fixed bottom-0 left-0 right-0 bg-brand-bg/90 backdrop-blur-xl border-t border-brand-border py-4 px-6 z-50 overflow-hidden">
                <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
                    <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded bg-gradient-to-br from-brand-primary to-brand-secondary opacity-80 flex-shrink-0 hidden sm:block" />
                        <div className="min-w-0 pr-4">
                            <div className="text-brand-text font-bold truncate max-w-[200px] sm:max-w-md">{script.title}</div>
                            <div className="text-brand-muted text-xs font-mono">{script.estimatedDuration} • {script.totalWords} words</div>
                        </div>
                    </div>

                    <div className="flex items-center gap-3 w-full sm:w-auto">
                        <button
                            onClick={handleShare}
                            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-full border border-brand-border hover:border-brand-primary text-brand-text hover:text-brand-primary bg-brand-bg hover:bg-brand-primary/10 transition-colors text-sm font-medium"
                        >
                            {shared ? <Check className="w-4 h-4 text-brand-secondary" /> : <Share2 className="w-4 h-4" />}
                            {shared ? 'Link Copied!' : 'Share'}
                        </button>
                        <button
                            onClick={handleCopyTranscript}
                            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-full border border-brand-border hover:border-brand-text text-brand-text bg-brand-card hover:bg-brand-card-hover transition-colors text-sm font-medium"
                        >
                            {copied ? <Check className="w-4 h-4 text-brand-secondary" /> : <Copy className="w-4 h-4" />}
                            {copied ? 'Copied!' : 'Transcript'}
                        </button>
                        <a
                            href={audioUrl}
                            download="PaperCast-Episode.mp3"
                            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-6 py-2.5 rounded-full bg-transparent border-2 border-brand-primary text-brand-primary hover:bg-brand-primary hover:text-white transition-colors text-sm font-bold shadow-[0_0_15px_rgba(108,99,255,0.2)] hover:shadow-[0_0_20px_rgba(108,99,255,0.4)] whitespace-nowrap"
                        >
                            <Download className="w-4 h-4" /> Save MP3
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
}
