import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, Share2, Copy, Check } from 'lucide-react';
import { AudioPlayer } from '../components/AudioPlayer';
import { ChapterPill } from '../components/ChapterPill';
import { StepIndicator } from '../components/StepIndicator';
import { useAppContext } from '../context/AppContext';

// Parse "HH:MM:SS" or "MM:SS" timestamp strings into total seconds
function parseTimestamp(ts: string): number {
    if (!ts) return 0;
    const parts = ts.split(':').map(Number);
    if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
    if (parts.length === 2) return parts[0] * 60 + parts[1];
    return 0;
}

// Convert absolute seconds back to MM:SS or HH:MM:SS
function formatTimestamp(totalSeconds: number): string {
    const h = Math.floor(totalSeconds / 3600);
    const m = Math.floor((totalSeconds % 3600) / 60);
    const s = Math.floor(totalSeconds % 60);
    if (h > 0) {
        return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    }
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

// Helper to split text into chunks of 2-3 sentences
function splitIntoSentenceChunks(text: string, sentencesPerChunk: number = 3): string[] {
    const sentences = text.match(/[^.!?]+[.!?]+(?:\s+|$)/g) || [text];
    const chunks: string[] = [];
    let currentChunk = '';
    let count = 0;
    for (const s of sentences) {
        currentChunk += s;
        count++;
        if (count >= sentencesPerChunk) {
            chunks.push(currentChunk.trim());
            currentChunk = '';
            count = 0;
        }
    }
    if (currentChunk.trim()) {
        chunks.push(currentChunk.trim());
    }
    return chunks;
}

export function Listen() {
    const navigate = useNavigate();
    const { script, audioUrl } = useAppContext();

    const [activeDialogue, setActiveDialogue] = useState(-1);
    const [activeChapter, setActiveChapter] = useState(0);
    const [autoScroll, setAutoScroll] = useState(true);
    const [currentTime, setCurrentTime] = useState(0);
    const [copied, setCopied] = useState(false);
    const [shared, setShared] = useState(false);
    const transcriptRef = useRef<HTMLDivElement>(null);
    const audioRef = useRef<HTMLAudioElement | null>(null);

    const handleShare = async () => {
        const shareData = {
            title: script?.title ?? 'PaperCast Episode',
            text: `🎙️ Listen to "${script?.title}" — generated by PaperCast`,
            url: window.location.href,
        };
        if (navigator.share && navigator.canShare(shareData)) {
            try { await navigator.share(shareData); } catch { /* user cancelled */ }
        } else {
            // Fallback: copy the URL to clipboard
            await navigator.clipboard.writeText(window.location.href);
            setShared(true);
            setTimeout(() => setShared(false), 2000);
        }
    };

    const handleCopyTranscript = async () => {
        if (!script) return;
        const lines = script.chapters.flatMap(ch => [
            `\n── ${ch.title} ──`,
            ...ch.dialogues.map(d => `[${d.timestamp}] ${d.speaker.toUpperCase()}: ${d.text}`)
        ]);
        const text = `${script.title}\n${'─'.repeat(60)}\n${lines.join('\n')}`;
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    if (!script || !audioUrl) {
        return (
            <div className="min-h-screen flex items-center justify-center flex-col gap-4 text-brand-muted">
                <h2 className="text-xl">No audio available.</h2>
                <button onClick={() => navigate('/edit')} className="text-brand-primary hover:underline">Go back to Editor</button>
            </div>
        );
    }

    // Flatten dialogues for transcript with cumulative seconds
    const rawDialogues = script.chapters.flatMap((c, cIdx) =>
        c.dialogues.map((d) => ({
            ...d,
            chapterIndex: cIdx,
            isAlex: d.speaker.toLowerCase() === 'alex',
            startSeconds: parseTimestamp(d.timestamp)
        }))
    );

    const allDialogues: (typeof rawDialogues[0] & { isContinuation?: boolean })[] = [];

    for (let i = 0; i < rawDialogues.length; i++) {
        const current = rawDialogues[i];
        const next = i + 1 < rawDialogues.length ? rawDialogues[i + 1] : null;

        // Estimate duration of this dialogue
        let duration = 0;
        if (next) {
            duration = Math.max(0, next.startSeconds - current.startSeconds);
        } else {
            // Rough estimate: 150 words per minute ~ 2.5 words per second
            const words = current.text.split(/\s+/).length;
            duration = words / 2.5;
        }

        // Split text into chunks of 2-3 sentences
        const chunks = splitIntoSentenceChunks(current.text, 2); // default to 2 sentences per chunk
        const totalChars = Math.max(1, current.text.length); // prevent div by zero
        let elapsedChars = 0;

        for (let j = 0; j < chunks.length; j++) {
            const chunk = chunks[j];
            const chunkStartTime = current.startSeconds + (elapsedChars / totalChars) * duration;

            allDialogues.push({
                ...current,
                text: chunk,
                startSeconds: chunkStartTime,
                timestamp: formatTimestamp(chunkStartTime),
                isContinuation: j > 0 // optional flag if we don't want to re-render speaker pic
            });

            elapsedChars += chunk.length;
        }
    }

    // Sync active dialogue based on current playback time
    useEffect(() => {
        let activeIdx = -1;
        for (let i = 0; i < allDialogues.length; i++) {
            if (currentTime >= allDialogues[i].startSeconds) {
                activeIdx = i;
            }
        }
        setActiveDialogue(activeIdx);

        // Update active chapter
        if (activeIdx >= 0) {
            setActiveChapter(allDialogues[activeIdx].chapterIndex);
        }
    }, [currentTime]);

    // Auto-scroll active dialogue into view
    useEffect(() => {
        if (!autoScroll || !transcriptRef.current) return;
        const active = transcriptRef.current.querySelector('[data-active="true"]');
        if (active) {
            active.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }, [activeDialogue, autoScroll]);

    // Seek audio to a specific dialogue when transcript is clicked
    const handleTranscriptClick = (dialogue: typeof allDialogues[0]) => {
        if (audioRef.current) {
            audioRef.current.currentTime = dialogue.startSeconds;
            // If paused, start playing
            audioRef.current.play().catch(() => { });
            setCurrentTime(dialogue.startSeconds);
        }
    };

    return (
        <div className="min-h-screen pt-24 pb-32 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
            <StepIndicator currentStep={5} />

            <div className="text-center mb-10">
                <h1 className="text-3xl md:text-4xl font-display font-bold mb-3">{script.title}</h1>
                <p className="text-brand-muted text-lg font-mono">Total Duration: {script.estimatedDuration}</p>
            </div>

            <div className="mb-12">
                <AudioPlayer
                    audioUrl={audioUrl}
                    title={script.title}
                    duration={script.estimatedDuration}
                    audioRef={audioRef}
                    onTimeUpdate={(t) => setCurrentTime(t)}
                />
            </div>

            <div className="mb-8">
                <div className="flex items-center justify-between mb-4">
                    <h2 className="text-xs font-bold text-brand-muted tracking-widest uppercase">Chapters</h2>
                    <div className="flex items-center gap-2">
                        <span className="text-xs text-brand-muted mr-2">Auto-scroll</span>
                        <button
                            onClick={() => setAutoScroll(!autoScroll)}
                            className={`w-10 h-5 rounded-full p-1 transition-colors ${autoScroll ? 'bg-brand-primary' : 'bg-brand-border'}`}
                        >
                            <div className={`w-3 h-3 rounded-full bg-white transition-transform ${autoScroll ? 'translate-x-5' : 'translate-x-0'}`} />
                        </button>
                    </div>
                </div>

                <div className="flex overflow-x-auto pb-4 gap-3 no-scrollbar mask-edges">
                    {script.chapters.map((chapter, i) => (
                        <ChapterPill
                            key={i}
                            title={chapter.title}
                            timestamp={chapter.dialogues[0]?.timestamp || "00:00"}
                            isActive={activeChapter === i}
                            onClick={() => {
                                setActiveChapter(i);
                                // Jump audio to first dialogue of this chapter
                                const firstDialogue = allDialogues.find(d => d.chapterIndex === i);
                                if (firstDialogue) handleTranscriptClick(firstDialogue);
                            }}
                        />
                    ))}
                </div>
            </div>

            {/* Live Transcript Feature */}
            <div className="bg-brand-card/50 border border-brand-border rounded-3xl p-6 sm:p-10 relative overflow-hidden">
                <div className="absolute top-0 left-0 right-0 h-16 bg-gradient-to-b from-brand-card/50 to-transparent z-10 pointer-events-none" />

                <div
                    ref={transcriptRef}
                    className="space-y-8 relative z-0 h-[500px] overflow-y-auto pr-4 custom-scrollbar"
                >
                    {allDialogues.map((dialogue, idx) => {
                        const state = idx === activeDialogue ? 'active' : idx < activeDialogue ? 'past' : 'future';

                        return (
                            <div
                                key={idx}
                                data-active={state === 'active'}
                                onClick={() => handleTranscriptClick(dialogue)}
                                title="Click to jump to this part"
                                className={`flex items-start gap-4 transition-all duration-500 cursor-pointer group
                   ${state === 'active'
                                        ? 'opacity-100 scale-100 filter drop-shadow-[0_0_15px_rgba(255,255,255,0.1)]'
                                        : state === 'past'
                                            ? 'opacity-40 scale-95 grayscale hover:opacity-70 hover:grayscale-0'
                                            : 'opacity-60 scale-95 hover:opacity-80'
                                    }
                   ${!dialogue.isAlex ? 'flex-row-reverse text-right' : ''}
                 `}
                            >
                                <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 font-bold border-2 transition-all
                   ${(dialogue as any).isContinuation ? 'opacity-0' : ''}
                   ${dialogue.isAlex
                                        ? state === 'active' ? 'bg-brand-primary text-white border-brand-primary' : 'bg-[#1A1A2E] text-brand-primary border-brand-border group-hover:border-brand-primary'
                                        : state === 'active' ? 'bg-brand-secondary text-[#0A0A0F] border-brand-secondary' : 'bg-[#1A2E2A] text-brand-secondary border-brand-border group-hover:border-brand-secondary'
                                    }
                 `}>
                                    {dialogue.isAlex ? 'A' : 'S'}
                                </div>

                                <div className={`flex-1 rounded-xl transition-all duration-300 ${state === 'active' ? 'bg-white/5 border border-white/10 p-4' : 'p-2 group-hover:bg-white/3'}`}>
                                    <div className="flex items-center gap-2 mb-1.5">
                                        <span className="font-mono text-xs text-brand-muted">{dialogue.timestamp}</span>
                                        {state !== 'active' && (
                                            <span className="opacity-0 group-hover:opacity-100 transition-opacity text-[10px] text-brand-muted/70 font-mono">
                                                ▶ click to jump
                                            </span>
                                        )}
                                    </div>
                                    <p className={`text-lg leading-relaxed ${state === 'active' ? 'text-white font-medium' : 'text-brand-text'}`}>
                                        {dialogue.text}
                                    </p>
                                </div>
                            </div>
                        );
                    })}
                </div>

                <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-brand-card/90 to-transparent z-10 pointer-events-none" />
            </div>

            {/* Sticky Bottom Bar for Export */}
            <div className="fixed bottom-0 left-0 right-0 bg-brand-bg/90 backdrop-blur-xl border-t border-brand-border py-4 px-6 z-50 overflow-hidden">
                <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
                    <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded bg-gradient-to-br from-brand-primary to-brand-secondary opacity-80 flex-shrink-0 hidden sm:block" />
                        <div className="min-w-0 pr-4">
                            <div className="text-brand-text font-bold truncate max-w-[200px] sm:max-w-md">{script.title}</div>
                            <div className="text-brand-muted text-xs font-mono">{script.estimatedDuration} • {script.totalWords} words</div>
                        </div>
                    </div>

                    <div className="flex items-center gap-3 w-full sm:w-auto">
                        <button
                            onClick={handleShare}
                            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-full border border-brand-border hover:border-brand-primary text-brand-text hover:text-brand-primary bg-brand-bg hover:bg-brand-primary/10 transition-colors text-sm font-medium"
                        >
                            {shared ? <Check className="w-4 h-4 text-brand-secondary" /> : <Share2 className="w-4 h-4" />}
                            {shared ? 'Link Copied!' : 'Share'}
                        </button>
                        <button
                            onClick={handleCopyTranscript}
                            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-full border border-brand-border hover:border-brand-text text-brand-text bg-brand-card hover:bg-[#20202A] transition-colors text-sm font-medium"
                        >
                            {copied ? <Check className="w-4 h-4 text-brand-secondary" /> : <Copy className="w-4 h-4" />}
                            {copied ? 'Copied!' : 'Transcript'}
                        </button>
                        <a
                            href={audioUrl}
                            download="PaperCast-Episode.mp3"
                            className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-6 py-2.5 rounded-full bg-transparent border-2 border-brand-primary text-brand-primary hover:bg-brand-primary hover:text-white transition-colors text-sm font-bold shadow-[0_0_15px_rgba(108,99,255,0.2)] hover:shadow-[0_0_20px_rgba(108,99,255,0.4)] whitespace-nowrap"
                        >
                            <Download className="w-4 h-4" /> Save MP3
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
}
